const STATE_STARTUP = 0
const STATE_INTRO = 1
const STATE_MAP = 2
const STATE_ENTERING_CITY = 3
const STATE_CITY = 4
const STATE_RUMORS = 5

const CITY_ARRIVE_DISTANCE = 60
const CITY_LEAVE_DISTANCE = 70
